---
abstract: 'see if all the unit tests are actually written'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-TestCoverage
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::Manifest: 0
  File::Spec: 0
  Pod::Parser: 0
  Test::More: 0.47
  Test::UseAllModules: 0.10
version: 0.01
