---
abstract: 'Test if your test covers all "public" subroutines of the package'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-TestCoverage
requires:
  B: '0'
  Devel::Symdump: '0'
  Exporter: '0'
  Test::Builder: '0'
  perl: '5.006001'
resources:
  bugtracker: http://github.com/reneeb/Test-TestCoverage/issues
  homepage: http://github.com/reneeb/Test-TestCoverage
  repository: http://github.com/reneeb/Test-TestCoverage.git
version: '0.12'
