# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-TestCoverage
version:      0.05
version_from: lib/Test/TestCoverage.pm
installdirs:  site
requires:
    Devel::Symdump:                0
    Exporter:                      0
    Hook::LexWrap:                 0
    Test::Builder:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
